### PR TITLE
Typescript task

### PR DESCRIPTION
**Pull request by VolframL**
Add typescript to app

### CODE REVIEW

**Comment by dellirom** [comment]
Couldn't find previous functionality, including the health-check endpoint

**Comment by dellirom** [comment]
Not everything has been rewritten to TS
There is *.js file import

**Comment by VolframL** [comment]
@dellirom update tsconfig, and previous functionality all works

**Comment by VolframL** [comment]
@dellirom check updates please

**Review by SergiiGEpam — APPROVED** [review]
All requirements are fulfilled

**Pull request merged**
